<?php

/**
 * @file
 * Contains react_app.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function react_app_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the react_app module.
    case 'help.page.react_app':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('React app boilerplate for progressive decoupling.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function react_app_theme() {
  return [
    'react_app' => [
      'variables' => ['entity_id' => NULL,],
      'render element' => 'children',
    ],
  ];
}
